
services:
  postgres:
    image: postgres:17-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/tests:/tests 
      - ./logs:/logs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - hemiron-net
    restart: unless-stopped

volumes:
  pgadmin-data:
  postgres-data: 
networks:
  hemiron-net:
    driver: bridge
