version: '3.9'

services:
  postgres:
    image: postgres:17-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - hemiron-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "80:80"  # Verbind poort 80 op de host naar poort 80 op de container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com  # Je pgAdmin login email
      - PGADMIN_DEFAULT_PASSWORD=admin  # Je pgAdmin login wachtwoord
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Behoud pgAdmin instellingen
    networks:
      - hemiron-net

  db-init:
    image: python:3.11
    depends_on:
      - postgres
    volumes:
      - ./database:/app  # Bind mount de lokale database directory naar /app in de container
    working_dir: /app    # Stel de werkdirectory in als /app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: >
      sh -c "pip install -r requirements.txt &&
             python setup_db.py"
    networks:
      - hemiron-net

volumes:
  pgadmin-data:

networks:
  hemiron-net:
    driver: bridge
